// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockDoor.Data.Contexts;

#nullable disable

namespace MockDoor.Data.Migrations.SqlServer
{
    [DbContext(typeof(MockDoorMainContext))]
    partial class MockDoorMainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MockDoor.Data.Models.Headers.RequestHeader", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ServiceRequestID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ServiceRequestID");

                    b.ToTable("RequestHeaders");
                });

            modelBuilder.Entity("MockDoor.Data.Models.Headers.ResponseHeader", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("MockResponseID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MockResponseID");

                    b.ToTable("ResponseHeaders");
                });

            modelBuilder.Entity("MockDoor.Data.Models.Headers.ServiceHeader", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("Enabled")
                        .HasDefaultValue(true)
                        .HasColumnType("bit");

                    b.Property<bool>("Incoming")
                        .HasColumnType("bit");

                    b.Property<int>("MicroserviceID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Outgoing")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("MicroserviceID");

                    b.ToTable("ServiceHeaders");
                });

            modelBuilder.Entity("MockDoor.Data.Models.Microservice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("Enabled")
                        .HasDefaultValue(true)
                        .HasColumnType("bit");

                    b.Property<int>("FakeDelay")
                        .HasColumnType("int");

                    b.Property<int>("HeadersMode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PassThroughTenant")
                        .HasDefaultValue(true)
                        .HasColumnType("bit");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ProxyMode")
                        .HasColumnType("bit");

                    b.Property<bool>("RandomiseMockResult")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceGroupID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SimulateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetUrl")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ServiceGroupID");

                    b.ToTable("Microservices");
                });

            modelBuilder.Entity("MockDoor.Data.Models.MockResponse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Enabled")
                        .HasDefaultValue(true)
                        .HasColumnType("bit");

                    b.Property<int>("Encoding")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Latency")
                        .HasColumnType("time");

                    b.Property<int>("Priority")
                        .HasDefaultValue(100)
                        .HasColumnType("int");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("MockResponses");
                });

            modelBuilder.Entity("MockDoor.Data.Models.QueryParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("QueryParameters");
                });

            modelBuilder.Entity("MockDoor.Data.Models.ServiceGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DefaultHealthCheckUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Enabled")
                        .HasDefaultValue(true)
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SimulateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TenantID");

                    b.ToTable("ServiceGroups");
                });

            modelBuilder.Entity("MockDoor.Data.Models.ServiceRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasDefaultValue(true)
                        .HasColumnType("bit");

                    b.Property<bool>("ExactUrlMatch")
                        .HasColumnType("bit");

                    b.Property<bool>("ExpectAuthHeader")
                        .HasColumnType("bit");

                    b.Property<string>("FromBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MicroserviceID")
                        .HasColumnType("int");

                    b.Property<int>("MockBehaviour")
                        .HasColumnType("int");

                    b.Property<int>("RestType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SimulateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TTLTicks")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("MicroserviceID");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("MockDoor.Data.Models.Tenant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SimulateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("MockDoor.Data.Models.Headers.RequestHeader", b =>
                {
                    b.HasOne("MockDoor.Data.Models.ServiceRequest", null)
                        .WithMany("RequestHeaders")
                        .HasForeignKey("ServiceRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MockDoor.Data.Models.Headers.ResponseHeader", b =>
                {
                    b.HasOne("MockDoor.Data.Models.MockResponse", null)
                        .WithMany("Headers")
                        .HasForeignKey("MockResponseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MockDoor.Data.Models.Headers.ServiceHeader", b =>
                {
                    b.HasOne("MockDoor.Data.Models.Microservice", null)
                        .WithMany("Headers")
                        .HasForeignKey("MicroserviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MockDoor.Data.Models.Microservice", b =>
                {
                    b.HasOne("MockDoor.Data.Models.ServiceGroup", "ServiceGroup")
                        .WithMany("Microservices")
                        .HasForeignKey("ServiceGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("MockDoor.Data.Models.MockResponse", b =>
                {
                    b.HasOne("MockDoor.Data.Models.ServiceRequest", "ServiceRequest")
                        .WithMany("MockResponses")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("MockDoor.Data.Models.QueryParameter", b =>
                {
                    b.HasOne("MockDoor.Data.Models.ServiceRequest", "ServiceRequest")
                        .WithMany("QueryParameters")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("MockDoor.Data.Models.ServiceGroup", b =>
                {
                    b.HasOne("MockDoor.Data.Models.Tenant", "Tenant")
                        .WithMany("ServiceGroups")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MockDoor.Data.Models.ServiceRequest", b =>
                {
                    b.HasOne("MockDoor.Data.Models.Microservice", "Microservice")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("MicroserviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Microservice");
                });

            modelBuilder.Entity("MockDoor.Data.Models.Microservice", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("MockDoor.Data.Models.MockResponse", b =>
                {
                    b.Navigation("Headers");
                });

            modelBuilder.Entity("MockDoor.Data.Models.ServiceGroup", b =>
                {
                    b.Navigation("Microservices");
                });

            modelBuilder.Entity("MockDoor.Data.Models.ServiceRequest", b =>
                {
                    b.Navigation("MockResponses");

                    b.Navigation("QueryParameters");

                    b.Navigation("RequestHeaders");
                });

            modelBuilder.Entity("MockDoor.Data.Models.Tenant", b =>
                {
                    b.Navigation("ServiceGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
